googleadservices.com
adservice.google.com
adservice.google.ca
pagead2.googlesyndication.com
googlesyndication.com
googletagservices.com
doubleclick.net
g.doubleclick.net
ad.doubleclick.net
securepubads.g.doubleclick.net
partner.googleadservices.com
adclick.g.doubleclick.net
cm.g.doubleclick.net
ads.google.com
ads.google.ca
ads.youtube.com
tpc.googlesyndication.com
s0.2mdn.net
static.doubleclick.net
